---
apiVersion: v1
kind: Secret
metadata:
  name: alexgroom-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23DevRHEL/alexgroom-gateway-gitops
